name: Tests

on: pull_request

jobs:
  lint-python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install system dependencies
      run: |
        pip3 install flake8 black

    - name: Lint Python
      run: python3 -m flake8 canonicalwebteam tests && python3 -m black --line-length 79 --check canonicalwebteam tests

  test-python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install system dependencies
      run: |
        sudo apt update && sudo apt install -y --no-install-recommends python3-setuptools

    - name: Test Python
      run: python3 setup.py test

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install system dependencies
      run: |
        sudo apt update && sudo apt install -y --no-install-recommends python3-setuptools python3-wheel
        pip3 install twine

    - name: Build package
      run: python3 setup.py sdist bdist_wheel

    - name: Twine check
      run: python3 -m twine check dist/*
